# -*- encoding: utf-8 -*-
"""
 Created by Ênio Viana at 15/05/2021
"""
from py_dss_interface.models.Example.ExampleBase import ExampleBase

dss = ExampleBase("13").dss

# Integer methods
print(45 * '=' + ' Integer Methods' + 45 * '=')
print(f'dss.loads_first(): {dss.first()}')
print(f'dss.loads_next(): {dss.next()}')
print(f'dss.loads_read_idx(): {dss.idx_read()}')
print(f'dss.loads_write_idx(): {dss.idx_write(1)}')
print(f'dss.loads_count(): {dss._count()}')
print(f'dss.loads_read_class(): {dss.class_read()}')
print(f'dss.loads_write_class(): {dss.class_write(1)}')
print(f'dss.loads_read_class(): {dss.class_read()}')
print(f'dss.loads_read_model(): {dss.model_read()}')
print(f'dss.loads_write_model(): {dss.model_write(2)}')
print(f'dss.loads_read_model(): {dss.model_read()}')
print(f'dss.loads_read_num_cust(): {dss.num_cust_read()}')
print(f'dss.loads_write_num_cust(): {dss.num_cust_write(12)}')
print(f'dss.loads_read_num_cust(): {dss.num_cust_read()}')
print(f'dss.loads_read_status(): {dss.status_read()}')
print(f'dss.loads_write_status(): {dss.status_write(1)}')
print(f'dss.loads_read_status(): {dss.status_read()}')
print(f'dss.loads_read_is_delta(): {dss.is_delta()}')
print(f'dss.loads_write_is_delta(): {dss.is_delta_write(0)}')
print(f'dss.loads_read_is_delta(): {dss.is_delta()}')

# String methods
print(45 * '=' + ' String Methods' + 45 * '=')
print(f'dss.loads_read_name(): {dss.name_read()}')
print(f'dss.loads_write_name(): {dss.name_write("634a")}')
print(f'dss.loads_read_name(): {dss.name_read()}')
print(f'dss.loads_read_cvr_curve(): {dss.cvr_curve_read()}')
# print(f'dss.loads_write_cvr_curve(): {dss.loads_write_cvr_curve("")}')
print(f'dss.loads_read_daily(): {dss.daily_read()}')
# print(f'dss.loads_write_daily(): {dss.loads_write_daily("")}')
print(f'dss.loads_read_daily(): {dss.daily_read()}')
print(f'dss.loads_read_duty(): {dss.duty_read()}')
# print(f'dss.loads_write_duty(): {dss.loads_write_duty("12")}')
print(f'dss.loads_read_duty(): {dss.duty_read()}')
print(f'dss.loads_read_spectrum(): {dss.spectrum_read()}')
# print(f'dss.loads_write_spectrum(): {dss.loads_write_spectrum("")}')
print(f'dss.loads_read_spectrum(): {dss.spectrum_read()}')
print(f'dss.loads_read_yearly(): {dss.yearly_read()}')
# print(f'dss.loads_write_yearly(): {dss.loads_write_yearly("")}')
print(f'dss.loads_read_yearly(): {dss.yearly_read()}')
print(f'dss.loads_read_growth(): {dss.growth_read()}')
# print(f'dss.loads_write_growth(): {dss.loads_write_growth("")}')
print(f'dss.loads_read_growth(): {dss.growth_read()}')

# Float methods
print(45 * '=' + ' Float Methods' + 45 * '=')
print(f'dss.loads_read_kw(): {dss.kw_read()}')
print(f'dss.loads_write_kw(): {dss.kw_write(123.1)}')
print(f'dss.loads_read_kw(): {dss.kw_read()}')
print(f'dss.loads_read_kv(): {dss.kv_read()}')
print(f'dss.loads_write_kv(): {dss.kv_write(123.1)}')
print(f'dss.loads_read_kv(): {dss.kv_read()}')
print(f'dss.loads_read_kvar(): {dss.kvar_read()}')
print(f'dss.loads_write_kvar(): {dss.kvar_write(123.1)}')
print(f'dss.loads_read_kvar(): {dss.kvar_read()}')
print(f'dss.loads_read_pf(): {dss.pf_read()}')
print(f'dss.loads_write_pf(): {dss.pf_write(123.1)}')
print(f'dss.loads_read_pf(): {dss.pf_read()}')
print(f'dss.loads_read_pct_mean(): {dss.pct_mean_read()}')
print(f'dss.loads_write_pct_mean(): {dss.pct_mean_write(123.1)}')
print(f'dss.loads_read_pct_mean(): {dss.pct_mean_read()}')
print(f'dss.loads_read_pct_std_dev(): {dss.pct_std_dev_read()}')
print(f'dss.loads_write_pct_std_dev(): {dss.pct_std_dev_write(123.1)}')
print(f'dss.loads_read_pct_std_dev(): {dss.pct_std_dev_read()}')
print(f'dss.loads_read_allocation_factor(): {dss.allocation_factor_read()}')
print(f'dss.loads_write_allocation_factor(): {dss.allocation_factor_write(123.1)}')
print(f'dss.loads_read_allocation_factor(): {dss.allocation_factor_read()}')
print(f'dss.loads_read_c_factor(): {dss.c_factor_read()}')
print(f'dss.loads_write_c_factor(): {dss.c_factor_write(123.1)}')
print(f'dss.loads_read_c_factor(): {dss.c_factor_read()}')
print(f'dss.loads_read_cvr_watts(): {dss.cvr_watts_read()}')
print(f'dss.loads_write_cvr_watts(): {dss.cvr_watts_write(123.1)}')
print(f'dss.loads_read_cvr_watts(): {dss.cvr_watts_read()}')
print(f'dss.loads_read_cvr_vars(): {dss.cvr_vars_read()}')
print(f'dss.loads_write_cvr_vars(): {dss.cvr_vars_write(123.1)}')
print(f'dss.loads_read_cvr_vars(): {dss.cvr_vars_read()}')
print(f'dss.loads_read_kva(): {dss.kva_read()}')
print(f'dss.loads_write_kva(): {dss.kva_write(123.1)}')
print(f'dss.loads_read_kva(): {dss.kva_read()}')
print(f'dss.loads_read_kwh(): {dss.kwh_read()}')
print(f'dss.loads_write_kwh(): {dss.kwh_write(123.1)}')
print(f'dss.loads_read_kwh(): {dss.kwh_read()}')
print(f'dss.loads_read_kwh_days(): {dss.kwh_days_read()}')
print(f'dss.loads_write_kwh_days(): {dss.kwh_days_write(123.1)}')
print(f'dss.loads_read_kwh_days(): {dss.kwh_days_read()}')
print(f'dss.loads_read_r_neut(): {dss.r_neut_read()}')
print(f'dss.loads_write_r_neut(): {dss.r_neut_write(123.1)}')
print(f'dss.loads_read_r_neut(): {dss.r_neut_read()}')
print(f'dss.loads_read_vmax_pu(): {dss.vmax_pu_read()}')
print(f'dss.loads_write_vmax_pu(): {dss.loads_write_vmax_pu(123.1)}')
print(f'dss.loads_read_vmax_pu(): {dss.vmax_pu_read()}')
print(f'dss.loads_read_vmin_emerg(): {dss.vmin_emerg_read()}')
print(f'dss.loads_write_vmin_emerg(): {dss.vmin_emerg_write(123.1)}')
print(f'dss.loads_read_vmin_emerg(): {dss.vmin_emerg_read()}')
print(f'dss.loads_read_vmin_norm(): {dss.vmin_norm_read()}')
print(f'dss.loads_write_vmin_norm(): {dss.vmin_norm_write(123.1)}')
print(f'dss.loads_read_vmin_norm(): {dss.vmin_norm_read()}')
print(f'dss.loads_read_vmin_pu(): {dss.vmin_pu_read()}')
print(f'dss.loads_write_vmin_pu(): {dss.vmin_pu_write(123.1)}')
print(f'dss.loads_read_vmin_pu(): {dss.vmin_pu_read()}')
print(f'dss.loads_read_xfkva(): {dss.xfkva_read()}')
print(f'dss.loads_write_xfkva(): {dss.xfkva_write(123.1)}')
print(f'dss.loads_read_xfkva(): {dss.xfkva_read()}')
print(f'dss.loads_read_x_neut(): {dss.x_neut_read()}')
print(f'dss.loads_write_x_neut(): {dss.x_neut_write(123.1)}')
print(f'dss.loads_read_x_neut(): {dss.x_neut_read()}')
print(f'dss.loads_read_pct_series_rl(): {dss.rl_read()}')
print(f'dss.loads_write_pct_series_rl(): {dss.rl_write(123.1)}')
print(f'dss.loads_read_pct_series_rl(): {dss.rl_read()}')
print(f'dss.loads_read_rel_weight(): {dss.rel_weight_read()}')
print(f'dss.loads_write_rel_weight(): {dss.rel_weight_write(123.1)}')
print(f'dss.loads_read_rel_weight(): {dss.rel_weight_read()}')


# Variant methods
print(45 * '=' + ' Variant Methods' + 45 * '=')
print(f'dss.loads_all_names(): {dss.names()}')
print(f'dss.loads_read_zipv(): {dss.zipv_read()}')
print(f'dss.loads_write_zipv(): {dss.zipv_write("[1 2 3 4 5 6 7]")}')
print(f'dss.loads_read_zipv(): {dss.zipv_read()}')
